# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shonenada/Proj/cGeDBIT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shonenada/Proj/cGeDBIT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shonenada/Proj/cGeDBIT/CMakeFiles /home/shonenada/Proj/cGeDBIT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shonenada/Proj/cGeDBIT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cGeDBIT

# Build rule for target.
cGeDBIT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT
.PHONY : cGeDBIT

# fast build rule for target.
cGeDBIT/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT.dir/build.make CMakeFiles/cGeDBIT.dir/build
.PHONY : cGeDBIT/fast

#=============================================================================
# Target rules for targets named cGeDBIT_indexalgorithms

# Build rule for target.
cGeDBIT_indexalgorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT_indexalgorithms
.PHONY : cGeDBIT_indexalgorithms

# fast build rule for target.
cGeDBIT_indexalgorithms/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/build
.PHONY : cGeDBIT_indexalgorithms/fast

#=============================================================================
# Target rules for targets named cGeDBIT_indexs

# Build rule for target.
cGeDBIT_indexs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT_indexs
.PHONY : cGeDBIT_indexs

# fast build rule for target.
cGeDBIT_indexs/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/build
.PHONY : cGeDBIT_indexs/fast

#=============================================================================
# Target rules for targets named cGeDBIT_metrics

# Build rule for target.
cGeDBIT_metrics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT_metrics
.PHONY : cGeDBIT_metrics

# fast build rule for target.
cGeDBIT_metrics/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/build
.PHONY : cGeDBIT_metrics/fast

#=============================================================================
# Target rules for targets named cGeDBIT_objects

# Build rule for target.
cGeDBIT_objects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT_objects
.PHONY : cGeDBIT_objects

# fast build rule for target.
cGeDBIT_objects/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/build
.PHONY : cGeDBIT_objects/fast

#=============================================================================
# Target rules for targets named cGeDBIT_querys

# Build rule for target.
cGeDBIT_querys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT_querys
.PHONY : cGeDBIT_querys

# fast build rule for target.
cGeDBIT_querys/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/build
.PHONY : cGeDBIT_querys/fast

#=============================================================================
# Target rules for targets named cGeDBIT_utils

# Build rule for target.
cGeDBIT_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cGeDBIT_utils
.PHONY : cGeDBIT_utils

# fast build rule for target.
cGeDBIT_utils/fast:
	$(MAKE) -f CMakeFiles/cGeDBIT_utils.dir/build.make CMakeFiles/cGeDBIT_utils.dir/build
.PHONY : cGeDBIT_utils/fast

src/SourceFiles/index/EcludedMiddleForest.o: src/SourceFiles/index/EcludedMiddleForest.cpp.o
.PHONY : src/SourceFiles/index/EcludedMiddleForest.o

# target to build an object file
src/SourceFiles/index/EcludedMiddleForest.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/EcludedMiddleForest.cpp.o
.PHONY : src/SourceFiles/index/EcludedMiddleForest.cpp.o

src/SourceFiles/index/EcludedMiddleForest.i: src/SourceFiles/index/EcludedMiddleForest.cpp.i
.PHONY : src/SourceFiles/index/EcludedMiddleForest.i

# target to preprocess a source file
src/SourceFiles/index/EcludedMiddleForest.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/EcludedMiddleForest.cpp.i
.PHONY : src/SourceFiles/index/EcludedMiddleForest.cpp.i

src/SourceFiles/index/EcludedMiddleForest.s: src/SourceFiles/index/EcludedMiddleForest.cpp.s
.PHONY : src/SourceFiles/index/EcludedMiddleForest.s

# target to generate assembly for a file
src/SourceFiles/index/EcludedMiddleForest.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/EcludedMiddleForest.cpp.s
.PHONY : src/SourceFiles/index/EcludedMiddleForest.cpp.s

src/SourceFiles/index/Index.o: src/SourceFiles/index/Index.cpp.o
.PHONY : src/SourceFiles/index/Index.o

# target to build an object file
src/SourceFiles/index/Index.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/Index.cpp.o
.PHONY : src/SourceFiles/index/Index.cpp.o

src/SourceFiles/index/Index.i: src/SourceFiles/index/Index.cpp.i
.PHONY : src/SourceFiles/index/Index.i

# target to preprocess a source file
src/SourceFiles/index/Index.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/Index.cpp.i
.PHONY : src/SourceFiles/index/Index.cpp.i

src/SourceFiles/index/Index.s: src/SourceFiles/index/Index.cpp.s
.PHONY : src/SourceFiles/index/Index.s

# target to generate assembly for a file
src/SourceFiles/index/Index.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/Index.cpp.s
.PHONY : src/SourceFiles/index/Index.cpp.s

src/SourceFiles/index/IndexNode.o: src/SourceFiles/index/IndexNode.cpp.o
.PHONY : src/SourceFiles/index/IndexNode.o

# target to build an object file
src/SourceFiles/index/IndexNode.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/IndexNode.cpp.o
.PHONY : src/SourceFiles/index/IndexNode.cpp.o

src/SourceFiles/index/IndexNode.i: src/SourceFiles/index/IndexNode.cpp.i
.PHONY : src/SourceFiles/index/IndexNode.i

# target to preprocess a source file
src/SourceFiles/index/IndexNode.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/IndexNode.cpp.i
.PHONY : src/SourceFiles/index/IndexNode.cpp.i

src/SourceFiles/index/IndexNode.s: src/SourceFiles/index/IndexNode.cpp.s
.PHONY : src/SourceFiles/index/IndexNode.s

# target to generate assembly for a file
src/SourceFiles/index/IndexNode.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/IndexNode.cpp.s
.PHONY : src/SourceFiles/index/IndexNode.cpp.s

src/SourceFiles/index/ListIndex.o: src/SourceFiles/index/ListIndex.cpp.o
.PHONY : src/SourceFiles/index/ListIndex.o

# target to build an object file
src/SourceFiles/index/ListIndex.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/ListIndex.cpp.o
.PHONY : src/SourceFiles/index/ListIndex.cpp.o

src/SourceFiles/index/ListIndex.i: src/SourceFiles/index/ListIndex.cpp.i
.PHONY : src/SourceFiles/index/ListIndex.i

# target to preprocess a source file
src/SourceFiles/index/ListIndex.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/ListIndex.cpp.i
.PHONY : src/SourceFiles/index/ListIndex.cpp.i

src/SourceFiles/index/ListIndex.s: src/SourceFiles/index/ListIndex.cpp.s
.PHONY : src/SourceFiles/index/ListIndex.s

# target to generate assembly for a file
src/SourceFiles/index/ListIndex.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/ListIndex.cpp.s
.PHONY : src/SourceFiles/index/ListIndex.cpp.s

src/SourceFiles/index/MVPIndex.o: src/SourceFiles/index/MVPIndex.cpp.o
.PHONY : src/SourceFiles/index/MVPIndex.o

# target to build an object file
src/SourceFiles/index/MVPIndex.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPIndex.cpp.o
.PHONY : src/SourceFiles/index/MVPIndex.cpp.o

src/SourceFiles/index/MVPIndex.i: src/SourceFiles/index/MVPIndex.cpp.i
.PHONY : src/SourceFiles/index/MVPIndex.i

# target to preprocess a source file
src/SourceFiles/index/MVPIndex.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPIndex.cpp.i
.PHONY : src/SourceFiles/index/MVPIndex.cpp.i

src/SourceFiles/index/MVPIndex.s: src/SourceFiles/index/MVPIndex.cpp.s
.PHONY : src/SourceFiles/index/MVPIndex.s

# target to generate assembly for a file
src/SourceFiles/index/MVPIndex.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPIndex.cpp.s
.PHONY : src/SourceFiles/index/MVPIndex.cpp.s

src/SourceFiles/index/MVPInternalNode.o: src/SourceFiles/index/MVPInternalNode.cpp.o
.PHONY : src/SourceFiles/index/MVPInternalNode.o

# target to build an object file
src/SourceFiles/index/MVPInternalNode.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPInternalNode.cpp.o
.PHONY : src/SourceFiles/index/MVPInternalNode.cpp.o

src/SourceFiles/index/MVPInternalNode.i: src/SourceFiles/index/MVPInternalNode.cpp.i
.PHONY : src/SourceFiles/index/MVPInternalNode.i

# target to preprocess a source file
src/SourceFiles/index/MVPInternalNode.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPInternalNode.cpp.i
.PHONY : src/SourceFiles/index/MVPInternalNode.cpp.i

src/SourceFiles/index/MVPInternalNode.s: src/SourceFiles/index/MVPInternalNode.cpp.s
.PHONY : src/SourceFiles/index/MVPInternalNode.s

# target to generate assembly for a file
src/SourceFiles/index/MVPInternalNode.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPInternalNode.cpp.s
.PHONY : src/SourceFiles/index/MVPInternalNode.cpp.s

src/SourceFiles/index/MVPLeafNode.o: src/SourceFiles/index/MVPLeafNode.cpp.o
.PHONY : src/SourceFiles/index/MVPLeafNode.o

# target to build an object file
src/SourceFiles/index/MVPLeafNode.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPLeafNode.cpp.o
.PHONY : src/SourceFiles/index/MVPLeafNode.cpp.o

src/SourceFiles/index/MVPLeafNode.i: src/SourceFiles/index/MVPLeafNode.cpp.i
.PHONY : src/SourceFiles/index/MVPLeafNode.i

# target to preprocess a source file
src/SourceFiles/index/MVPLeafNode.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPLeafNode.cpp.i
.PHONY : src/SourceFiles/index/MVPLeafNode.cpp.i

src/SourceFiles/index/MVPLeafNode.s: src/SourceFiles/index/MVPLeafNode.cpp.s
.PHONY : src/SourceFiles/index/MVPLeafNode.s

# target to generate assembly for a file
src/SourceFiles/index/MVPLeafNode.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexs.dir/build.make CMakeFiles/cGeDBIT_indexs.dir/src/SourceFiles/index/MVPLeafNode.cpp.s
.PHONY : src/SourceFiles/index/MVPLeafNode.cpp.s

src/SourceFiles/indexalgorithm/BalancePartitionMethod.o: src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/BalancePartitionMethod.o

# target to build an object file
src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.o

src/SourceFiles/indexalgorithm/BalancePartitionMethod.i: src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/BalancePartitionMethod.i

# target to preprocess a source file
src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.i

src/SourceFiles/indexalgorithm/BalancePartitionMethod.s: src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/BalancePartitionMethod.s

# target to generate assembly for a file
src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/BalancePartitionMethod.cpp.s

src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.o: src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.o

# target to build an object file
src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.o

src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.i: src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.i

# target to preprocess a source file
src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.i

src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.s: src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.s

# target to generate assembly for a file
src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.cpp.s

src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.o: src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.o

# target to build an object file
src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.o

src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.i: src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.i

# target to preprocess a source file
src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.i

src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.s: src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.s

# target to generate assembly for a file
src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.cpp.s

src/SourceFiles/indexalgorithm/PartitionResults.o: src/SourceFiles/indexalgorithm/PartitionResults.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/PartitionResults.o

# target to build an object file
src/SourceFiles/indexalgorithm/PartitionResults.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/PartitionResults.cpp.o
.PHONY : src/SourceFiles/indexalgorithm/PartitionResults.cpp.o

src/SourceFiles/indexalgorithm/PartitionResults.i: src/SourceFiles/indexalgorithm/PartitionResults.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/PartitionResults.i

# target to preprocess a source file
src/SourceFiles/indexalgorithm/PartitionResults.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/PartitionResults.cpp.i
.PHONY : src/SourceFiles/indexalgorithm/PartitionResults.cpp.i

src/SourceFiles/indexalgorithm/PartitionResults.s: src/SourceFiles/indexalgorithm/PartitionResults.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/PartitionResults.s

# target to generate assembly for a file
src/SourceFiles/indexalgorithm/PartitionResults.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_indexalgorithms.dir/build.make CMakeFiles/cGeDBIT_indexalgorithms.dir/src/SourceFiles/indexalgorithm/PartitionResults.cpp.s
.PHONY : src/SourceFiles/indexalgorithm/PartitionResults.cpp.s

src/SourceFiles/metric/DNAMetric.o: src/SourceFiles/metric/DNAMetric.cpp.o
.PHONY : src/SourceFiles/metric/DNAMetric.o

# target to build an object file
src/SourceFiles/metric/DNAMetric.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/DNAMetric.cpp.o
.PHONY : src/SourceFiles/metric/DNAMetric.cpp.o

src/SourceFiles/metric/DNAMetric.i: src/SourceFiles/metric/DNAMetric.cpp.i
.PHONY : src/SourceFiles/metric/DNAMetric.i

# target to preprocess a source file
src/SourceFiles/metric/DNAMetric.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/DNAMetric.cpp.i
.PHONY : src/SourceFiles/metric/DNAMetric.cpp.i

src/SourceFiles/metric/DNAMetric.s: src/SourceFiles/metric/DNAMetric.cpp.s
.PHONY : src/SourceFiles/metric/DNAMetric.s

# target to generate assembly for a file
src/SourceFiles/metric/DNAMetric.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/DNAMetric.cpp.s
.PHONY : src/SourceFiles/metric/DNAMetric.cpp.s

src/SourceFiles/metric/EditDistance.o: src/SourceFiles/metric/EditDistance.cpp.o
.PHONY : src/SourceFiles/metric/EditDistance.o

# target to build an object file
src/SourceFiles/metric/EditDistance.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/EditDistance.cpp.o
.PHONY : src/SourceFiles/metric/EditDistance.cpp.o

src/SourceFiles/metric/EditDistance.i: src/SourceFiles/metric/EditDistance.cpp.i
.PHONY : src/SourceFiles/metric/EditDistance.i

# target to preprocess a source file
src/SourceFiles/metric/EditDistance.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/EditDistance.cpp.i
.PHONY : src/SourceFiles/metric/EditDistance.cpp.i

src/SourceFiles/metric/EditDistance.s: src/SourceFiles/metric/EditDistance.cpp.s
.PHONY : src/SourceFiles/metric/EditDistance.s

# target to generate assembly for a file
src/SourceFiles/metric/EditDistance.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/EditDistance.cpp.s
.PHONY : src/SourceFiles/metric/EditDistance.cpp.s

src/SourceFiles/metric/EuclideanDistance.o: src/SourceFiles/metric/EuclideanDistance.cpp.o
.PHONY : src/SourceFiles/metric/EuclideanDistance.o

# target to build an object file
src/SourceFiles/metric/EuclideanDistance.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/EuclideanDistance.cpp.o
.PHONY : src/SourceFiles/metric/EuclideanDistance.cpp.o

src/SourceFiles/metric/EuclideanDistance.i: src/SourceFiles/metric/EuclideanDistance.cpp.i
.PHONY : src/SourceFiles/metric/EuclideanDistance.i

# target to preprocess a source file
src/SourceFiles/metric/EuclideanDistance.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/EuclideanDistance.cpp.i
.PHONY : src/SourceFiles/metric/EuclideanDistance.cpp.i

src/SourceFiles/metric/EuclideanDistance.s: src/SourceFiles/metric/EuclideanDistance.cpp.s
.PHONY : src/SourceFiles/metric/EuclideanDistance.s

# target to generate assembly for a file
src/SourceFiles/metric/EuclideanDistance.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/EuclideanDistance.cpp.s
.PHONY : src/SourceFiles/metric/EuclideanDistance.cpp.s

src/SourceFiles/metric/ImageMetric.o: src/SourceFiles/metric/ImageMetric.cpp.o
.PHONY : src/SourceFiles/metric/ImageMetric.o

# target to build an object file
src/SourceFiles/metric/ImageMetric.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/ImageMetric.cpp.o
.PHONY : src/SourceFiles/metric/ImageMetric.cpp.o

src/SourceFiles/metric/ImageMetric.i: src/SourceFiles/metric/ImageMetric.cpp.i
.PHONY : src/SourceFiles/metric/ImageMetric.i

# target to preprocess a source file
src/SourceFiles/metric/ImageMetric.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/ImageMetric.cpp.i
.PHONY : src/SourceFiles/metric/ImageMetric.cpp.i

src/SourceFiles/metric/ImageMetric.s: src/SourceFiles/metric/ImageMetric.cpp.s
.PHONY : src/SourceFiles/metric/ImageMetric.s

# target to generate assembly for a file
src/SourceFiles/metric/ImageMetric.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/ImageMetric.cpp.s
.PHONY : src/SourceFiles/metric/ImageMetric.cpp.s

src/SourceFiles/metric/MSMSMetric.o: src/SourceFiles/metric/MSMSMetric.cpp.o
.PHONY : src/SourceFiles/metric/MSMSMetric.o

# target to build an object file
src/SourceFiles/metric/MSMSMetric.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/MSMSMetric.cpp.o
.PHONY : src/SourceFiles/metric/MSMSMetric.cpp.o

src/SourceFiles/metric/MSMSMetric.i: src/SourceFiles/metric/MSMSMetric.cpp.i
.PHONY : src/SourceFiles/metric/MSMSMetric.i

# target to preprocess a source file
src/SourceFiles/metric/MSMSMetric.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/MSMSMetric.cpp.i
.PHONY : src/SourceFiles/metric/MSMSMetric.cpp.i

src/SourceFiles/metric/MSMSMetric.s: src/SourceFiles/metric/MSMSMetric.cpp.s
.PHONY : src/SourceFiles/metric/MSMSMetric.s

# target to generate assembly for a file
src/SourceFiles/metric/MSMSMetric.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/MSMSMetric.cpp.s
.PHONY : src/SourceFiles/metric/MSMSMetric.cpp.s

src/SourceFiles/metric/Metric.o: src/SourceFiles/metric/Metric.cpp.o
.PHONY : src/SourceFiles/metric/Metric.o

# target to build an object file
src/SourceFiles/metric/Metric.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/Metric.cpp.o
.PHONY : src/SourceFiles/metric/Metric.cpp.o

src/SourceFiles/metric/Metric.i: src/SourceFiles/metric/Metric.cpp.i
.PHONY : src/SourceFiles/metric/Metric.i

# target to preprocess a source file
src/SourceFiles/metric/Metric.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/Metric.cpp.i
.PHONY : src/SourceFiles/metric/Metric.cpp.i

src/SourceFiles/metric/Metric.s: src/SourceFiles/metric/Metric.cpp.s
.PHONY : src/SourceFiles/metric/Metric.s

# target to generate assembly for a file
src/SourceFiles/metric/Metric.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/Metric.cpp.s
.PHONY : src/SourceFiles/metric/Metric.cpp.s

src/SourceFiles/metric/RNAMetric.o: src/SourceFiles/metric/RNAMetric.cpp.o
.PHONY : src/SourceFiles/metric/RNAMetric.o

# target to build an object file
src/SourceFiles/metric/RNAMetric.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/RNAMetric.cpp.o
.PHONY : src/SourceFiles/metric/RNAMetric.cpp.o

src/SourceFiles/metric/RNAMetric.i: src/SourceFiles/metric/RNAMetric.cpp.i
.PHONY : src/SourceFiles/metric/RNAMetric.i

# target to preprocess a source file
src/SourceFiles/metric/RNAMetric.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/RNAMetric.cpp.i
.PHONY : src/SourceFiles/metric/RNAMetric.cpp.i

src/SourceFiles/metric/RNAMetric.s: src/SourceFiles/metric/RNAMetric.cpp.s
.PHONY : src/SourceFiles/metric/RNAMetric.s

# target to generate assembly for a file
src/SourceFiles/metric/RNAMetric.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_metrics.dir/build.make CMakeFiles/cGeDBIT_metrics.dir/src/SourceFiles/metric/RNAMetric.cpp.s
.PHONY : src/SourceFiles/metric/RNAMetric.cpp.s

src/SourceFiles/objects/DNA.o: src/SourceFiles/objects/DNA.cpp.o
.PHONY : src/SourceFiles/objects/DNA.o

# target to build an object file
src/SourceFiles/objects/DNA.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DNA.cpp.o
.PHONY : src/SourceFiles/objects/DNA.cpp.o

src/SourceFiles/objects/DNA.i: src/SourceFiles/objects/DNA.cpp.i
.PHONY : src/SourceFiles/objects/DNA.i

# target to preprocess a source file
src/SourceFiles/objects/DNA.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DNA.cpp.i
.PHONY : src/SourceFiles/objects/DNA.cpp.i

src/SourceFiles/objects/DNA.s: src/SourceFiles/objects/DNA.cpp.s
.PHONY : src/SourceFiles/objects/DNA.s

# target to generate assembly for a file
src/SourceFiles/objects/DNA.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DNA.cpp.s
.PHONY : src/SourceFiles/objects/DNA.cpp.s

src/SourceFiles/objects/DoubleIndexObjectPair.o: src/SourceFiles/objects/DoubleIndexObjectPair.cpp.o
.PHONY : src/SourceFiles/objects/DoubleIndexObjectPair.o

# target to build an object file
src/SourceFiles/objects/DoubleIndexObjectPair.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DoubleIndexObjectPair.cpp.o
.PHONY : src/SourceFiles/objects/DoubleIndexObjectPair.cpp.o

src/SourceFiles/objects/DoubleIndexObjectPair.i: src/SourceFiles/objects/DoubleIndexObjectPair.cpp.i
.PHONY : src/SourceFiles/objects/DoubleIndexObjectPair.i

# target to preprocess a source file
src/SourceFiles/objects/DoubleIndexObjectPair.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DoubleIndexObjectPair.cpp.i
.PHONY : src/SourceFiles/objects/DoubleIndexObjectPair.cpp.i

src/SourceFiles/objects/DoubleIndexObjectPair.s: src/SourceFiles/objects/DoubleIndexObjectPair.cpp.s
.PHONY : src/SourceFiles/objects/DoubleIndexObjectPair.s

# target to generate assembly for a file
src/SourceFiles/objects/DoubleIndexObjectPair.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DoubleIndexObjectPair.cpp.s
.PHONY : src/SourceFiles/objects/DoubleIndexObjectPair.cpp.s

src/SourceFiles/objects/DoubleVector.o: src/SourceFiles/objects/DoubleVector.cpp.o
.PHONY : src/SourceFiles/objects/DoubleVector.o

# target to build an object file
src/SourceFiles/objects/DoubleVector.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DoubleVector.cpp.o
.PHONY : src/SourceFiles/objects/DoubleVector.cpp.o

src/SourceFiles/objects/DoubleVector.i: src/SourceFiles/objects/DoubleVector.cpp.i
.PHONY : src/SourceFiles/objects/DoubleVector.i

# target to preprocess a source file
src/SourceFiles/objects/DoubleVector.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DoubleVector.cpp.i
.PHONY : src/SourceFiles/objects/DoubleVector.cpp.i

src/SourceFiles/objects/DoubleVector.s: src/SourceFiles/objects/DoubleVector.cpp.s
.PHONY : src/SourceFiles/objects/DoubleVector.s

# target to generate assembly for a file
src/SourceFiles/objects/DoubleVector.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/DoubleVector.cpp.s
.PHONY : src/SourceFiles/objects/DoubleVector.cpp.s

src/SourceFiles/objects/Image.o: src/SourceFiles/objects/Image.cpp.o
.PHONY : src/SourceFiles/objects/Image.o

# target to build an object file
src/SourceFiles/objects/Image.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/Image.cpp.o
.PHONY : src/SourceFiles/objects/Image.cpp.o

src/SourceFiles/objects/Image.i: src/SourceFiles/objects/Image.cpp.i
.PHONY : src/SourceFiles/objects/Image.i

# target to preprocess a source file
src/SourceFiles/objects/Image.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/Image.cpp.i
.PHONY : src/SourceFiles/objects/Image.cpp.i

src/SourceFiles/objects/Image.s: src/SourceFiles/objects/Image.cpp.s
.PHONY : src/SourceFiles/objects/Image.s

# target to generate assembly for a file
src/SourceFiles/objects/Image.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/Image.cpp.s
.PHONY : src/SourceFiles/objects/Image.cpp.s

src/SourceFiles/objects/IndexObject.o: src/SourceFiles/objects/IndexObject.cpp.o
.PHONY : src/SourceFiles/objects/IndexObject.o

# target to build an object file
src/SourceFiles/objects/IndexObject.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/IndexObject.cpp.o
.PHONY : src/SourceFiles/objects/IndexObject.cpp.o

src/SourceFiles/objects/IndexObject.i: src/SourceFiles/objects/IndexObject.cpp.i
.PHONY : src/SourceFiles/objects/IndexObject.i

# target to preprocess a source file
src/SourceFiles/objects/IndexObject.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/IndexObject.cpp.i
.PHONY : src/SourceFiles/objects/IndexObject.cpp.i

src/SourceFiles/objects/IndexObject.s: src/SourceFiles/objects/IndexObject.cpp.s
.PHONY : src/SourceFiles/objects/IndexObject.s

# target to generate assembly for a file
src/SourceFiles/objects/IndexObject.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/IndexObject.cpp.s
.PHONY : src/SourceFiles/objects/IndexObject.cpp.s

src/SourceFiles/objects/RNA.o: src/SourceFiles/objects/RNA.cpp.o
.PHONY : src/SourceFiles/objects/RNA.o

# target to build an object file
src/SourceFiles/objects/RNA.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/RNA.cpp.o
.PHONY : src/SourceFiles/objects/RNA.cpp.o

src/SourceFiles/objects/RNA.i: src/SourceFiles/objects/RNA.cpp.i
.PHONY : src/SourceFiles/objects/RNA.i

# target to preprocess a source file
src/SourceFiles/objects/RNA.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/RNA.cpp.i
.PHONY : src/SourceFiles/objects/RNA.cpp.i

src/SourceFiles/objects/RNA.s: src/SourceFiles/objects/RNA.cpp.s
.PHONY : src/SourceFiles/objects/RNA.s

# target to generate assembly for a file
src/SourceFiles/objects/RNA.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/RNA.cpp.s
.PHONY : src/SourceFiles/objects/RNA.cpp.s

src/SourceFiles/objects/StringObject.o: src/SourceFiles/objects/StringObject.cpp.o
.PHONY : src/SourceFiles/objects/StringObject.o

# target to build an object file
src/SourceFiles/objects/StringObject.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/StringObject.cpp.o
.PHONY : src/SourceFiles/objects/StringObject.cpp.o

src/SourceFiles/objects/StringObject.i: src/SourceFiles/objects/StringObject.cpp.i
.PHONY : src/SourceFiles/objects/StringObject.i

# target to preprocess a source file
src/SourceFiles/objects/StringObject.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/StringObject.cpp.i
.PHONY : src/SourceFiles/objects/StringObject.cpp.i

src/SourceFiles/objects/StringObject.s: src/SourceFiles/objects/StringObject.cpp.s
.PHONY : src/SourceFiles/objects/StringObject.s

# target to generate assembly for a file
src/SourceFiles/objects/StringObject.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/StringObject.cpp.s
.PHONY : src/SourceFiles/objects/StringObject.cpp.s

src/SourceFiles/objects/TandemSpectra.o: src/SourceFiles/objects/TandemSpectra.cpp.o
.PHONY : src/SourceFiles/objects/TandemSpectra.o

# target to build an object file
src/SourceFiles/objects/TandemSpectra.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/TandemSpectra.cpp.o
.PHONY : src/SourceFiles/objects/TandemSpectra.cpp.o

src/SourceFiles/objects/TandemSpectra.i: src/SourceFiles/objects/TandemSpectra.cpp.i
.PHONY : src/SourceFiles/objects/TandemSpectra.i

# target to preprocess a source file
src/SourceFiles/objects/TandemSpectra.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/TandemSpectra.cpp.i
.PHONY : src/SourceFiles/objects/TandemSpectra.cpp.i

src/SourceFiles/objects/TandemSpectra.s: src/SourceFiles/objects/TandemSpectra.cpp.s
.PHONY : src/SourceFiles/objects/TandemSpectra.s

# target to generate assembly for a file
src/SourceFiles/objects/TandemSpectra.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_objects.dir/build.make CMakeFiles/cGeDBIT_objects.dir/src/SourceFiles/objects/TandemSpectra.cpp.s
.PHONY : src/SourceFiles/objects/TandemSpectra.cpp.s

src/SourceFiles/query/Query.o: src/SourceFiles/query/Query.cpp.o
.PHONY : src/SourceFiles/query/Query.o

# target to build an object file
src/SourceFiles/query/Query.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/src/SourceFiles/query/Query.cpp.o
.PHONY : src/SourceFiles/query/Query.cpp.o

src/SourceFiles/query/Query.i: src/SourceFiles/query/Query.cpp.i
.PHONY : src/SourceFiles/query/Query.i

# target to preprocess a source file
src/SourceFiles/query/Query.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/src/SourceFiles/query/Query.cpp.i
.PHONY : src/SourceFiles/query/Query.cpp.i

src/SourceFiles/query/Query.s: src/SourceFiles/query/Query.cpp.s
.PHONY : src/SourceFiles/query/Query.s

# target to generate assembly for a file
src/SourceFiles/query/Query.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/src/SourceFiles/query/Query.cpp.s
.PHONY : src/SourceFiles/query/Query.cpp.s

src/SourceFiles/query/RangeQuery.o: src/SourceFiles/query/RangeQuery.cpp.o
.PHONY : src/SourceFiles/query/RangeQuery.o

# target to build an object file
src/SourceFiles/query/RangeQuery.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/src/SourceFiles/query/RangeQuery.cpp.o
.PHONY : src/SourceFiles/query/RangeQuery.cpp.o

src/SourceFiles/query/RangeQuery.i: src/SourceFiles/query/RangeQuery.cpp.i
.PHONY : src/SourceFiles/query/RangeQuery.i

# target to preprocess a source file
src/SourceFiles/query/RangeQuery.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/src/SourceFiles/query/RangeQuery.cpp.i
.PHONY : src/SourceFiles/query/RangeQuery.cpp.i

src/SourceFiles/query/RangeQuery.s: src/SourceFiles/query/RangeQuery.cpp.s
.PHONY : src/SourceFiles/query/RangeQuery.s

# target to generate assembly for a file
src/SourceFiles/query/RangeQuery.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_querys.dir/build.make CMakeFiles/cGeDBIT_querys.dir/src/SourceFiles/query/RangeQuery.cpp.s
.PHONY : src/SourceFiles/query/RangeQuery.cpp.s

src/SourceFiles/util/getopt.o: src/SourceFiles/util/getopt.cpp.o
.PHONY : src/SourceFiles/util/getopt.o

# target to build an object file
src/SourceFiles/util/getopt.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT_utils.dir/build.make CMakeFiles/cGeDBIT_utils.dir/src/SourceFiles/util/getopt.cpp.o
.PHONY : src/SourceFiles/util/getopt.cpp.o

src/SourceFiles/util/getopt.i: src/SourceFiles/util/getopt.cpp.i
.PHONY : src/SourceFiles/util/getopt.i

# target to preprocess a source file
src/SourceFiles/util/getopt.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT_utils.dir/build.make CMakeFiles/cGeDBIT_utils.dir/src/SourceFiles/util/getopt.cpp.i
.PHONY : src/SourceFiles/util/getopt.cpp.i

src/SourceFiles/util/getopt.s: src/SourceFiles/util/getopt.cpp.s
.PHONY : src/SourceFiles/util/getopt.s

# target to generate assembly for a file
src/SourceFiles/util/getopt.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT_utils.dir/build.make CMakeFiles/cGeDBIT_utils.dir/src/SourceFiles/util/getopt.cpp.s
.PHONY : src/SourceFiles/util/getopt.cpp.s

src/app/BuildMVPIndex.o: src/app/BuildMVPIndex.cpp.o
.PHONY : src/app/BuildMVPIndex.o

# target to build an object file
src/app/BuildMVPIndex.cpp.o:
	$(MAKE) -f CMakeFiles/cGeDBIT.dir/build.make CMakeFiles/cGeDBIT.dir/src/app/BuildMVPIndex.cpp.o
.PHONY : src/app/BuildMVPIndex.cpp.o

src/app/BuildMVPIndex.i: src/app/BuildMVPIndex.cpp.i
.PHONY : src/app/BuildMVPIndex.i

# target to preprocess a source file
src/app/BuildMVPIndex.cpp.i:
	$(MAKE) -f CMakeFiles/cGeDBIT.dir/build.make CMakeFiles/cGeDBIT.dir/src/app/BuildMVPIndex.cpp.i
.PHONY : src/app/BuildMVPIndex.cpp.i

src/app/BuildMVPIndex.s: src/app/BuildMVPIndex.cpp.s
.PHONY : src/app/BuildMVPIndex.s

# target to generate assembly for a file
src/app/BuildMVPIndex.cpp.s:
	$(MAKE) -f CMakeFiles/cGeDBIT.dir/build.make CMakeFiles/cGeDBIT.dir/src/app/BuildMVPIndex.cpp.s
.PHONY : src/app/BuildMVPIndex.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cGeDBIT"
	@echo "... cGeDBIT_indexalgorithms"
	@echo "... cGeDBIT_indexs"
	@echo "... cGeDBIT_metrics"
	@echo "... cGeDBIT_objects"
	@echo "... cGeDBIT_querys"
	@echo "... cGeDBIT_utils"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/SourceFiles/index/EcludedMiddleForest.o"
	@echo "... src/SourceFiles/index/EcludedMiddleForest.i"
	@echo "... src/SourceFiles/index/EcludedMiddleForest.s"
	@echo "... src/SourceFiles/index/Index.o"
	@echo "... src/SourceFiles/index/Index.i"
	@echo "... src/SourceFiles/index/Index.s"
	@echo "... src/SourceFiles/index/IndexNode.o"
	@echo "... src/SourceFiles/index/IndexNode.i"
	@echo "... src/SourceFiles/index/IndexNode.s"
	@echo "... src/SourceFiles/index/ListIndex.o"
	@echo "... src/SourceFiles/index/ListIndex.i"
	@echo "... src/SourceFiles/index/ListIndex.s"
	@echo "... src/SourceFiles/index/MVPIndex.o"
	@echo "... src/SourceFiles/index/MVPIndex.i"
	@echo "... src/SourceFiles/index/MVPIndex.s"
	@echo "... src/SourceFiles/index/MVPInternalNode.o"
	@echo "... src/SourceFiles/index/MVPInternalNode.i"
	@echo "... src/SourceFiles/index/MVPInternalNode.s"
	@echo "... src/SourceFiles/index/MVPLeafNode.o"
	@echo "... src/SourceFiles/index/MVPLeafNode.i"
	@echo "... src/SourceFiles/index/MVPLeafNode.s"
	@echo "... src/SourceFiles/indexalgorithm/BalancePartitionMethod.o"
	@echo "... src/SourceFiles/indexalgorithm/BalancePartitionMethod.i"
	@echo "... src/SourceFiles/indexalgorithm/BalancePartitionMethod.s"
	@echo "... src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.o"
	@echo "... src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.i"
	@echo "... src/SourceFiles/indexalgorithm/EcludedMiddlePartitionMethod.s"
	@echo "... src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.o"
	@echo "... src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.i"
	@echo "... src/SourceFiles/indexalgorithm/FFTPivotSelectionMethod.s"
	@echo "... src/SourceFiles/indexalgorithm/PartitionResults.o"
	@echo "... src/SourceFiles/indexalgorithm/PartitionResults.i"
	@echo "... src/SourceFiles/indexalgorithm/PartitionResults.s"
	@echo "... src/SourceFiles/metric/DNAMetric.o"
	@echo "... src/SourceFiles/metric/DNAMetric.i"
	@echo "... src/SourceFiles/metric/DNAMetric.s"
	@echo "... src/SourceFiles/metric/EditDistance.o"
	@echo "... src/SourceFiles/metric/EditDistance.i"
	@echo "... src/SourceFiles/metric/EditDistance.s"
	@echo "... src/SourceFiles/metric/EuclideanDistance.o"
	@echo "... src/SourceFiles/metric/EuclideanDistance.i"
	@echo "... src/SourceFiles/metric/EuclideanDistance.s"
	@echo "... src/SourceFiles/metric/ImageMetric.o"
	@echo "... src/SourceFiles/metric/ImageMetric.i"
	@echo "... src/SourceFiles/metric/ImageMetric.s"
	@echo "... src/SourceFiles/metric/MSMSMetric.o"
	@echo "... src/SourceFiles/metric/MSMSMetric.i"
	@echo "... src/SourceFiles/metric/MSMSMetric.s"
	@echo "... src/SourceFiles/metric/Metric.o"
	@echo "... src/SourceFiles/metric/Metric.i"
	@echo "... src/SourceFiles/metric/Metric.s"
	@echo "... src/SourceFiles/metric/RNAMetric.o"
	@echo "... src/SourceFiles/metric/RNAMetric.i"
	@echo "... src/SourceFiles/metric/RNAMetric.s"
	@echo "... src/SourceFiles/objects/DNA.o"
	@echo "... src/SourceFiles/objects/DNA.i"
	@echo "... src/SourceFiles/objects/DNA.s"
	@echo "... src/SourceFiles/objects/DoubleIndexObjectPair.o"
	@echo "... src/SourceFiles/objects/DoubleIndexObjectPair.i"
	@echo "... src/SourceFiles/objects/DoubleIndexObjectPair.s"
	@echo "... src/SourceFiles/objects/DoubleVector.o"
	@echo "... src/SourceFiles/objects/DoubleVector.i"
	@echo "... src/SourceFiles/objects/DoubleVector.s"
	@echo "... src/SourceFiles/objects/Image.o"
	@echo "... src/SourceFiles/objects/Image.i"
	@echo "... src/SourceFiles/objects/Image.s"
	@echo "... src/SourceFiles/objects/IndexObject.o"
	@echo "... src/SourceFiles/objects/IndexObject.i"
	@echo "... src/SourceFiles/objects/IndexObject.s"
	@echo "... src/SourceFiles/objects/RNA.o"
	@echo "... src/SourceFiles/objects/RNA.i"
	@echo "... src/SourceFiles/objects/RNA.s"
	@echo "... src/SourceFiles/objects/StringObject.o"
	@echo "... src/SourceFiles/objects/StringObject.i"
	@echo "... src/SourceFiles/objects/StringObject.s"
	@echo "... src/SourceFiles/objects/TandemSpectra.o"
	@echo "... src/SourceFiles/objects/TandemSpectra.i"
	@echo "... src/SourceFiles/objects/TandemSpectra.s"
	@echo "... src/SourceFiles/query/Query.o"
	@echo "... src/SourceFiles/query/Query.i"
	@echo "... src/SourceFiles/query/Query.s"
	@echo "... src/SourceFiles/query/RangeQuery.o"
	@echo "... src/SourceFiles/query/RangeQuery.i"
	@echo "... src/SourceFiles/query/RangeQuery.s"
	@echo "... src/SourceFiles/util/getopt.o"
	@echo "... src/SourceFiles/util/getopt.i"
	@echo "... src/SourceFiles/util/getopt.s"
	@echo "... src/app/BuildMVPIndex.o"
	@echo "... src/app/BuildMVPIndex.i"
	@echo "... src/app/BuildMVPIndex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

